name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  source:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate autoload
      run: composer dump-autoload -o

    - name: Linting PHP Syntax
      run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }} | grep '\.php$' || true)

          if [ -z "$CHANGED_FILES" ]; then
            echo "✅ Aucun fichier PHP modifié."
            exit 0
          fi

          echo "Fichiers PHP modifiés :"
          echo "$CHANGED_FILES"

          for file in $CHANGED_FILES; do
            echo "🔍 Lint $file"
            php -l "$file" || exit 1
          done

    - name: Linting PHPCS
      run: composer run-script phpcs || true # ! Need to remove 'true'

    - name: Format Checker
      run: composer run-script php-cs-fixer-no-changes || true # ! Need to remove 'true'
    
    - name: Run PHPStan Scan
      run: composer run-script analyse

  build:
    needs: source
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: xdebug
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate autoload
      run: composer dump-autoload -o

    - name: Unit testing
      run: composer run-script test

    - name: Code coverage
      run: composer run-script code-coverage

  test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v4
        - name: Cache Composer packages
          uses: actions/cache@v3
          with:
            path: vendor
            key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-php-

  preview:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

